[package]
name = "rjs"
version = "0.1.0"
authors = ["Jihyun Yu <yjh0502@gmail.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]
rustler = "0.18"
erlang_nif-sys = "0.6"
lazy_static = "1"
serde = "1"
serde_json = "1"
